### ISSUE TITLE
Who wants to buy an iPod touch in 2020, come on

### ISSUE THREAD

**Issue by AnshG714** [HackOurCampus/fullstack-integration-workshop#1]
^

**Comment by ashneeldas2** [comment]
I feel like the iPhone 5 is the bigger problem, pls create new issue

**Comment by meganyin13** [comment]
Hey hey those were the glory days

**Comment by meganyin13** [comment]
Steve Jobs was still alive 😭

**Comment by meganyin13** [comment]
should be fixed in https://github.com/HackOurCampus/fullstack-integration-workshop/commit/e9a247ae09f3af84dd5fe3ea43ceeeb921377615 🙄
